plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-angular.cjs
    spec: "https://github.com/bgotink/yarn-plugin-angular/raw/latest/bin/%40yarnpkg/plugin-angular.js"

yarnPath: .yarn/releases/yarn-berry.cjs

nodeLinker: node-modules
